### ISSUE TITLE
demo.html中这种调用无法通过，请问什么原因？ 报错：Uncaught ReferenceError: vue is not defined

### ISSUE THREAD

**Issue by aijj9898** [qq449245884/vue-okr-tree#12]
demo.html:
<meta charset="utf-8">
<title>vue-okr-tree demo</title>
<script src="./vue-okr-tree.umd.js"></script>

<link rel="stylesheet" href="./vue-okr-tree.css">

<script>
console.log(vue-okr-tree)
</script>

**Comment by qq449245884** [comment]
建议使用 npm 方式 ,cdn不太稳定！
