### ISSUE TITLE
【bug】垂直方向树，从第三层下面开始，如果只有单个节点，连接线会错乱

### ISSUE THREAD

**Issue by liux4ever** [qq449245884/vue-okr-tree#18]
![image](https://user-images.githubusercontent.com/34912330/132176764-1277894c-a15d-4212-9703-510c8d6286db.png)

数据如下图，请问是我数据的问题吗
![image](https://user-images.githubusercontent.com/34912330/132176927-f4ab1882-5f32-4dae-9522-2e7ada3e1a1a.png)

**Comment by liux4ever** [comment]
目前我的解决办法是给 is-leaf 加一个默认宽度（如140px），太小会导致往左缩，这样撑开就不会有错乱，感觉还是样式没有自适应的问题

**Comment by qq449245884** [comment]
更新一下最新的版本的
