### ISSUE TITLE
不支持异步修改data双向绑定的数据吗？

### ISSUE THREAD

**Issue by wadellg** [qq449245884/vue-okr-tree#2]
在mounted里接口返回数据初始化，页面不渲染，只有放在data里的静态数据才渲染。
试了同类的v-org-tree是可以的...

**Comment by captain883** [comment]
> 在mounted里接口返回数据初始化，页面不渲染，只有放在data里的静态数据才渲染。
> 试了同类的v-org-tree是可以的...

是的，我也发现了这个问题

**Comment by qq449245884** [comment]
你好，vue-okr-tree@1.0.5 已经修复这个问题
