### ISSUE TITLE
节点展开折叠的时候怎么保证操作的那个节点位置不变

### ISSUE THREAD

**Issue by ping813** [qq449245884/vue-okr-tree#21]
现在节点展开折叠的时候，节点总是动来动去的，尤其是子节点比较多的那些节点，操作完都不知道刚操作的那个节点位置变到哪里去了，怎么实现节点折叠展开操作不影响当前节点的位置

**Comment by qq449245884** [comment]
覆盖样式，使用定位的，不过需要计算对应的位置。

**Comment by qq449245884** [comment]
最新版本的已经实现了，请更新最新版本
