### ISSUE TITLE
npm i安装问题

### ISSUE THREAD

**Issue by CAOqian0624** [qq449245884/vue-okr-tree#23]
The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
目前我的node是16的版本，然后报这个错，是npm版本过高？

**Comment by qq449245884** [comment]
lock 删除在重新安装呢？
