### ISSUE TITLE
安装包内容不一样

### ISSUE THREAD

**Issue by yyman001** [qq449245884/vue-okr-tree#31]
现在这个问题导致, 我本地项目安装的正常, 到了jenkin就出了问题, 安装的npm内容跟本地的不一致
![image](https://user-images.githubusercontent.com/5688485/182334959-c0d82cb7-1fe5-48ef-807a-3615ab769580.png)

左边是单独在一个空文件夹里面使用 `yarn add vue-okr-tree@1.0.11` ,右边也是同样的命令, 但是安装查看包的内容确不一样...是否是源的问题呢?

**Comment by qq449245884** [comment]
已修复： 对应版本：vue-okr-tree@1.0.12

**Comment by qq449245884** [comment]
已修复： 对应版本：vue-okr-tree@1.0.12

**Comment by qq449245884** [comment]
已修复： 对应版本：vue-okr-tree@1.0.12
