### ISSUE TITLE
1.0.11版本不可用

### ISSUE THREAD

**Issue by zhangxl19951027** [qq449245884/vue-okr-tree#32]
项目install成功，然后启动项目，报错信息如下
![image](https://user-images.githubusercontent.com/44833226/183389844-020a60df-aa8d-4be8-a99c-0a7523f89066.png)
vue-okr-tree包文件截图
![image](https://user-images.githubusercontent.com/44833226/183390332-1a3f43b3-26d2-4009-928d-80b04cfd66d0.png)
![image](https://user-images.githubusercontent.com/44833226/183390388-06edfc55-18e4-43da-86bc-8703b2530b54.png)

切换回1.0.10版本，则可以正常使用。

**Comment by coder-yp** [comment]
确实有这个问题，希望尽快修复。

**Comment by qq449245884** [comment]
对应版本：vue-okr-tree@1.0.12

**Comment by qq449245884** [comment]
已修复
