### ISSUE TITLE
vue-okr-tree 如何在非单页面使用，直接在html页面引用

### ISSUE THREAD

**Issue by duyanming** [qq449245884/vue-okr-tree#42]
vue-okr-tree 如何在非单页面使用，直接在html页面引用

**Comment by duyanming** [comment]
![image](https://user-images.githubusercontent.com/17999146/216824035-262ee60f-d922-42bd-9142-82a20e3d0e24.png)
空白页，也没有报错

**Comment by qq449245884** [comment]
使用打包好的umd文件 哈
