### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by ghost** [qq449245884/vue-okr-tree#6]
您好，我想问一下为什么我通过CDN引入不了呢？控制台显示：vue-okr-tree.umd.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by qq449245884** [comment]
建议使用 npm 安装的方式 ,cdn 不太稳定。

**Comment by qq449245884** [comment]
建议使用 npm 安装的方式 ,cdn 不太稳定。
